/**
 * Vendor the web fonts into the repo.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Run by hand when the font list changes, like `npm run icons`. Not part of the
 * build: the output is committed, and a build that reached out to Google would
 * be the thing this script exists to remove.
 *
 * Why self-hosted (issue 18, and docs/STEAM.md S06):
 *
 *   - The `@import url(fonts.googleapis.com/...)` it replaces was a serial
 *     chain on the critical path -- parse our CSS, fetch Google's CSS, then
 *     fetch the fonts, across two hosts, before any text renders.
 *   - It disclosed every visitor's IP to Google on page load, before any
 *     interaction. That is the pattern the privacy policy would have to
 *     describe, and removing it is cheaper than describing it.
 *   - And the one that made this urgent rather than tidy: the Steam build is an
 *     *offline* application. Sigil has no illustrations -- it is typography and
 *     CSS -- so a player with no network was getting the whole game in Georgia
 *     and system-ui. visual/steam-build.spec.js caught it on the first run.
 *
 * Both families are SIL OFL, so self-hosting is permitted; the licence is
 * vendored alongside them in src/fonts/OFL.txt.
 *
 * The files land in src/fonts/ rather than public/fonts/, which is where issue
 * 18 suggested. public/ is copied verbatim and referenced by root-absolute
 * path, and a root-absolute path is exactly what breaks under itch's
 * subdirectory and the Steam build's file:// origin. Anything under src/ goes
 * through Vite's asset pipeline instead and comes out rebased against the
 * target's `base`.
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'src', 'fonts')

/**
 * The weights the app actually renders, checked against the source rather than
 * copied from the old @import.
 *
 * Inter 300 was in the import and is used by nothing -- no `font-light`
 * anywhere in src/ -- so it is dropped. Inter 400 is not requested by any class
 * but is the default weight of every unstyled run of body text, so it stays.
 * Cinzel is display-only and never appears below 500.
 */
const FAMILIES = 'Cinzel:wght@500;600;700&family=Inter:wght@400;500;600;700'

/** English game. latin-ext covers the accented characters a name might carry. */
const KEEP = new Set(['latin', 'latin-ext'])

// Google serves woff2 only to user agents it believes support it.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const cssUrl = `https://fonts.googleapis.com/css2?family=${FAMILIES}&display=swap`

const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } })
if (!res.ok) {
  console.error(`Font CSS request failed: ${res.status} ${res.statusText}`)
  process.exit(1)
}
const css = await res.text()

// Google's CSS is a run of `/* subset */ @font-face { ... }` pairs. The comment
// is the only place the subset name appears, so the pairing has to be parsed
// together rather than matching @font-face alone.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)]
if (blocks.length === 0) {
  console.error('Parsed no @font-face blocks; Google changed the CSS shape.')
  process.exit(1)
}

const field = (body, name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim()

rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })

const faces = []
for (const [, subset, body] of blocks) {
  if (!KEEP.has(subset)) continue

  const family = field(body, 'font-family')?.replace(/['"]/g, '')
  const weight = field(body, 'font-weight')
  const style = field(body, 'font-style') || 'normal'
  const range = field(body, 'unicode-range')
  const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
  if (!family || !weight || !url) continue

  const file = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`
  const font = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!font.ok) {
    console.error(`Failed to download ${file}: ${font.status}`)
    process.exit(1)
  }
  const bytes = Buffer.from(await font.arrayBuffer())
  writeFileSync(join(outDir, file), bytes)
  faces.push({ family, weight, style, range, file, bytes: bytes.length })
  console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)}KB`)
}

const header = `/*
 * Self-hosted web fonts. GENERATED by scripts/fetch-fonts.mjs -- do not edit.
 *
 * Replaces an @import to fonts.googleapis.com (issue 18). Three reasons, and
 * the third is the one that forced it: it was a render-blocking chain across
 * two hosts, it disclosed every visitor's IP to Google before any interaction,
 * and it left the offline Steam build rendering a typography-driven game in
 * fallback fonts.
 *
 * Paths are relative on purpose. Vite rebases and hashes them per target, which
 * is what keeps them resolving from itch's subdirectory and from the Steam
 * build's file:// origin. A root-absolute path would break both, silently.
 *
 * Cinzel and Inter are SIL OFL 1.1; see src/fonts/OFL.txt.
 */
`

const rules = faces.map(f => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`).join('\n\n')

writeFileSync(join(root, 'src', 'fonts.css'), `${header}\n${rules}\n`)

const total = faces.reduce((n, f) => n + f.bytes, 0)
console.log(`\n${faces.length} faces, ${(total / 1024).toFixed(1)}KB total -> src/fonts.css`)
console.log('Remember to keep src/fonts/OFL.txt alongside them.')
